version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.9
    build:
      context: ./docker/etcd/
      dockerfile: Dockerfile
    restart: always

  mysql:
    image: ghcr.io/douyu/prometheus:latest
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    restart: always

  prometheus:
    image: ghcr.io/douyu/prometheus:latest
    build:
      context: ./docker/prometheus/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - etcd

  grafana:
    image: ghcr.io/douyu/grafana:latest
    build:
      context: ./docker/grafana/
      dockerfile: Dockerfile
    depends_on:
      - juno-admin
      - prometheus

  juno-admin:
    image: ghcr.io/douyu/juno-admin:latest
    build:
      context: ./docker/juno-admin/
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - prometheus
      - etcd

