
name: docker-compose-actions-workflow
on: push
jobs:
  check-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start juno assembly and juno service
        run: docker-compose -f docker-compose.build.yml build
      - name: sleep 10s
        run: sleep 10
      - name: docker images
        run: docker ps
